name: update blog posts in GitHub readme

on: 
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  
jobs:
 update-readme-with-blog:
  name: 'Update the profile readme with the latest blog posts'
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: gautamkrishnar/blog-post-workflow@master
      with: 
        max_post_count: "5"
        feed_list: "https://www.visualstudiogeeks.com/rss.xml"